cc_library (
    name = "io_utils",
    hdrs = [
        "include/io_utils.hpp",
        "include/io_utils.inl"
    ],
    srcs = [
        "src/io_utils.cpp",
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
    copts = [
        "-lstdc++fs"
    ]
)
