cc_binary(
    name = "00",
    srcs = ["00.cpp"]
)

cc_binary(
    name = "01",
    srcs = ["01.cpp"]
)

cc_binary(
    name = "01_ylks",
    srcs = ["01_ylks.cpp"],
    deps = [
        "//src/cpp/third_parties/CLI11:CLI11",
        "//src/cpp/shared_libs/io_utils:io_utils"
    ],
    copts = [
        "-lstdc++fs"
    ]
)

cc_binary(
    name = "02_rk",
    srcs = ["02_rk.cpp"],
)

cc_binary(
    name = "02_ylks",
    srcs = ["02_ylks.cpp"],
    deps = [
        "//src/cpp/shared_libs/io_utils:io_utils"
    ],
    copts = [
        "-lstdc++fs"
    ]
)

cc_binary(
    name = "03_ylks",
    srcs = ["03_ylks.cpp"],
    deps = [
        "//src/cpp/shared_libs/io_utils:io_utils"
    ],
    copts = [
        "-lstdc++fs"
    ]
)

cc_binary(
    name = "04_ylks",
    srcs = ["04_ylks.cpp"],
    deps = [
        "//src/cpp/shared_libs/io_utils:io_utils"
    ]
)

cc_binary(
    name = "05_ylks",
    srcs = ["05_ylks.cpp"],
    deps = [
        "//src/cpp/shared_libs/io_utils:io_utils"
    ]
)
