name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v1
          with:
            python-version: '3.12'
      - name: Install Python dependency
        run: |
          python3 -m pip install --upgrade pip
          pip install numpy
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: nightly
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - name: Setup bazel
        uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Run tests
        env:
          AOC_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
        run: julia --color=yes ./runtests.jl
